export const residenceList = [
  {
    title: "Elgin (Boys)",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img8.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Daily Cleaning (Rooms+ Washrooms)",
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Asthapad (Girls)",
    location: "12A,Chakraberia Road, Near Terapanth Bhawan, Kolkata- 700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Individual Fridge",
        "Separate Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Lift",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Ajanta (Boys)",
    location: "93/2 Bokul Bagan Road Kolkata-700025",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img6.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Sienna (Boys)",
    location: "51B, Subhashini Ganguly Sarani, Kolkata-700025",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img3.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 17000 },
      { type: "DOUBLE-SHARING", price: 13000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Nivasa (Girls) ",
    location: "2No, Ho-Chi Min Sarani, Kolkata- 700070",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img2.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 18000 },
      { type: "TRIPLE-SHARING", price: 16000 },
      { type: "FOUR-SHARING", price: 16000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Shyamananda (Girls)",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img4.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Kankurgachi (Girls)",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img5.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Northern Park (Boys) ",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img7.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "NBCC (Girls)",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img9.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "37A Staywell (Boys) ",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img10.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Newtown Suparna Villa",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img11.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
  {
    title: "Hari (Girls)",
    location: "12C Sarat Bose Road, Kolkata-700020",
    contactInfo: {
      contactName: "Arihant Jain",
      contactNum: 7439368713,
    },
    mainSrc: [
      "/home/img12.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img4.png",
      "/more/img2.png",
    ],
    facilities: {
      dining: [
        "Three times Meal (Pure Veg)",
        "Morning tea & Evening Snacks",
        "Live kitchen",
        "Common Fridge",
        "Common Dining Space",
      ],
      security: ["24 Hours CCTV Security"],
      healthcare: [
        "Air Conditioner facility",
        "Television",
        "Wifi",
        "Aquaguard",
        "Daily Cleaning (Rooms+ Washrooms)",
      ],
    },
    bedTypes: [
      { type: "SINGLE NON-SHARING", price: 20000 },
      { type: "DOUBLE-SHARING", price: 17000 },
      { type: "TRIPLE-SHARING", price: 15000 },
      { type: "FOUR-SHARING", price: 15000 },
    ],
    additionalImages: [
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
      "/more/img1.png",
    ],
  },
];
